theme: jekyll-theme-minimal
title: Dr. Raj Krishna Mondal
description: Data Scientist, Infinite Analytics Pvt. Ltd. | Ph.D. in Computational Mathematics, MNNIT Ald | Deep Learning | Natural Language Processing | Big Data.
